spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# application-dev.yml
springdoc:
  show-actuator: true
  api-docs:
#    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
openapi:
  service:
    api-docs: identity-service
    server: http://localhost:${server.port}/identity
    title: Identity service
    version: 1.0.0
jwt:
  #  truy cap trang web de gen key: https://generate-random.org/ > encryption-key-generator
  signerKey: "dvIeRFqELCrrkkKY1bPk7/IHbaC6dlJerXr5/N2f6j0MdgGVDkaiO3Yc+2PIJ0Sv"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

